version: '3.3'

services:
  flask:
    build: .
    container_name: app_flask
    restart: always
    depends_on:
      - mysql
    ports:
      - "4000:4000"
    volumes:
      - ./backend-flask:/app

  mysql:
    image: 'mysql:5.7.13'
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      -  ./bd-mysql:/var/lib/mysql
    env_file:
      - common.env